TWITTER_API_KEY = "wWo1msZdiSH7AGbFuZU9LEgxb"
TWITTER_API_KEY_SECRET = "cX8bCDWWPLC60tNGL2bzWZbeEEJFtcfkZkWzoO7PqUn6LX0aGY"
TWITTER_ACCESS_TOKEN = "1038631070986633217-VuRjKCnQzkBkwk3nRbAoOdBw6BDYtB"
TWITTER_ACCESS_TOKEN_SECRET = "2ac7OykXJhldxI1rV06yIeOzRe0oudKaM928dTLW5GigT"
